### ISSUE TITLE
SMTP_AUTH variable missing from docs

### ISSUE THREAD

**Issue by TobiasDax** [docmost/docmost#119]
took me a while to find the pull request that added the SMTP_AUTH=true variable to docker to get mail sending to work. Would be great if it could be added to the documentation

**Comment by olivierIllogika** [comment]
Hey @TobiasDax , could you post a link to that pull request you mentioned? I can't find it. Thanks!

**Comment by wuast94** [comment]
i dont know if it relates to this but i cant get smtps to work. 

Logs when trying to resend the inventation: 

```
docmost_docmost.1.ycqje03064x7@swarm04    | 
docmost_docmost.1.ycqje03064x7@swarm04    | > docmost@0.2.8 start /app
docmost_docmost.1.ycqje03064x7@swarm04    | > pnpm --filter ./apps/server run start:prod
docmost_docmost.1.ycqje03064x7@swarm04    | 
docmost_docmost.1.ycqje03064x7@swarm04    | 
docmost_docmost.1.ycqje03064x7@swarm04    | > server@0.2.8 start:prod /app/apps/server
docmost_docmost.1.ycqje03064x7@swarm04    | > cross-env NODE_ENV=production node dist/main
docmost_docmost.1.ycqje03064x7@swarm04    | 
docmost_docmost.1.ycqje03064x7@swarm04    | (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
docmost_docmost.1.ycqje03064x7@swarm04    | (Use `node --trace-deprecation ...` to show where the warning was created)
docmost_docmost.1.ycqje03064x7@swarm04    | [Nest] 41  - 07/26/2024, 12:19:38 AM     LOG [NestFactory] Starting Nest application...
docmost_docmost.1.ycqje03064x7@swarm04    | [Nest] 41  - 07/26/2024, 12:19:38 AM     LOG [DatabaseModule] Establishing database connection
docmost_docmost.1.ycqje03064x7@swarm04    | [Nest] 41  - 07/26/2024, 12:19:38 AM     LOG [DatabaseModule] Database connection successful
docmost_docmost.1.ycqje03064x7@swarm04    | [Nest] 41  - 07/26/2024, 12:19:38 AM     LOG [DatabaseMigrationService] No pending database migrations
docmost_docmost.1.ycqje03064x7@swarm04    | [Nest] 41  - 07/26/2024, 12:19:38 AM     LOG [NestApplication] Nest application successfully started
docmost_docmost.1.ycqje03064x7@swarm04    | [Nest] 41  - 07/26/2024, 12:22:25 AM   ERROR [ExceptionsHandler] ERR Error running script (call to 29cda4b049edd8dde07e11bca9e4c60c322a416d): @user_script:248: script tried accessing undeclared key, key: bull:{email-queue}:3
docmost_docmost.1.ycqje03064x7@swarm04    | ReplyError: ERR Error running script (call to 29cda4b049edd8dde07e11bca9e4c60c322a416d): @user_script:248: script tried accessing undeclared key, key: bull:{email-queue}:3
docmost_docmost.1.ycqje03064x7@swarm04    |     at parseError (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
docmost_docmost.1.ycqje03064x7@swarm04    |     at parseType (/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
```

the error comes when i try to resend the inventation

**Comment by wuast94** [comment]
checked the redis part, `script tried accessing undeclared key, key: bull:{email-queue}:3`

```
127.0.0.1:6379> keys *
1) "bull:{email-queue}:id"
2) "bull:{email-queue}:meta"

127.0.0.1:6379> GET bull:{email-queue}:id
"4"

127.0.0.1:6379> HGETALL bull:{email-queue}:meta
1) "opts.maxLenEvents"
2) "10000"
```

i dont know about redis but if im right the key docmost try to access dont even exists?

**Comment by wuast94** [comment]
maybee he mean SMTP_SECURE ? dont know

**Comment by olivierIllogika** [comment]
> maybee he mean SMTP_SECURE ? dont know

Yes, that would make total sense.  It's my own PR that added SMTP_SECURE and modified an internal "auth" variable.  I really was looking for that SMTP_AUTH variable everywhere though 😅

**Comment by wuast94** [comment]
No problem, happy to help 😊

**Comment by TobiasDax** [comment]
Sorry for the late reply, i was on the road any for some reason guthub 2FA wont let me in on mobile devices.

What i meant was:
in the Documentation the config options for smtp are
```
MAIL_DRIVER=smtp
SMTP_HOST=
SMTP_PORT=
SMTP_USERNAME=
SMTP_PASSWORD=
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME=Docmost
```

but this did not work for me with my google workspace credentials (App Password generated for docmost)

After finding this PR https://github.com/docmost/docmost/pull/81 i tried adding
`SMTP_SECURE=true` to my config and now everything is working fine.

So my request is to add this line to the config in the documentation.
Sorry for confusing this more with the wrong variable name in the title, was a bit hectic :)

**Comment by Philipinho** [comment]
The documentation has been updated (https://github.com/docmost/docs/pull/3). Thanks to @olivierIllogika.
